name: Deploy Azure VM using Bicep

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: 'Test-Rg'
  AZURE_DEPLOYMENT_NAME: 'vmDeployment'
  AZURE_LOCATION: 'eastus'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Deploy Bicep
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
    #     template: ./bicep/main.bicep
    #     parameters: ./bicep/main.parameters.json

    - name: Delete resource group (destroys ALL resources)
      run: |
        az group delete \
          --name $AZURE_RESOURCE_GROUP \
          --yes --no-wait
